In [1]:
import numpy as np

## 1. Создайте массив `arr_1` размером 3х4, все элементы которого равны 3

In [2]:
arr_1 = np.full((3, 4), 3)

In [3]:
arr_1

array([[3, 3, 3, 3],
       [3, 3, 3, 3],
       [3, 3, 3, 3]])

## 2. Создайте массив `arr_2`, заполненный случайными целыми числами от 0 до 9, размером 2х4

In [4]:
arr_2 = np.random.randint(0, 10, (2, 4))

In [5]:
arr_2

array([[8, 1, 6, 2],
       [5, 6, 0, 5]], dtype=int32)

## 3. Выведите на экран количество элементов в созданных массивах `arr_1` и `arr_2`

In [6]:
arr_1.size

12

In [7]:
arr_2.size

8

## 4. Соедините массивы `arr_1` и `arr_2` по нулевой оси

In [8]:
np.vstack((arr_1, arr_2))

array([[3, 3, 3, 3],
       [3, 3, 3, 3],
       [3, 3, 3, 3],
       [8, 1, 6, 2],
       [5, 6, 0, 5]])

## 5. Создайте массив `arr_3` из кортежа чисел `(1, 8, 6, 5, 8, 3)` с помощью функции `np.array()`

In [9]:
arr_3 = np.array((1, 8, 6, 5, 8, 3))

In [10]:
arr_3

array([1, 8, 6, 5, 8, 3])

## 6. Умножьте каждый элемент массива `arr_3` на число 3 и прибавьте к каждому элементу 1. Результат записишите в новый массив `arr_4`

In [11]:
arr_4 = arr_3 * 3 + 1

In [12]:
arr_4

array([ 4, 25, 19, 16, 25, 10])

## 7. Преобразуйте массив `arr_3` к двумерному массиву 2х3. Результат запишите в массив `arr_5`

In [13]:
arr_5 = arr_3.reshape(2, 3)

In [14]:
arr_5

array([[1, 8, 6],
       [5, 8, 3]])

## 8. Определите минимальные элементы массива `arr_5` вдоль первой оси

In [15]:
np.min(arr_5, axis=1)

array([1, 3])

## 9. Вычислите среднее арифметическое всех элементов массива `arr_5`

In [16]:
np.mean(arr_5)

np.float64(5.166666666666667)

## 10. Создайте массив `arr_6`, состоящий из квадратов чисел от 0 до 10

In [17]:
arr_6 = np.arange(0, 11)**2

In [18]:
arr_6

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

## 11. Выведите каждый второй элемент массива `arr_6`

In [19]:
arr_6[::2]

array([  0,   4,  16,  36,  64, 100])

## 12. Выведите элементы массива `arr_6` в обратном порядке

In [20]:
arr_6[::-1]

array([100,  81,  64,  49,  36,  25,  16,   9,   4,   1,   0])

## 13. Каждому второму элементу массива `arr_6` присвойте значение 2

In [21]:
arr_6[::2] = 2

In [22]:
arr_6

array([ 2,  1,  2,  9,  2, 25,  2, 49,  2, 81,  2])

## 14. Проверьте, есть ли в массиве `arr_6` значение 49

In [23]:
np.any(arr_6 == 49)

np.True_

## 15. Создайте двумерный массив `A`, состоящий из положительных и отрицательных чисел. Из массива `A` выберите все отрицательные элементы и запишите их в одномерный массив `B`

In [24]:
A = np.random.randint(-9, 10, size = (3, 3))

In [25]:
A

array([[ 5,  9, -5],
       [-4,  3,  1],
       [ 1, -4, -9]], dtype=int32)

In [26]:
B = A[A < 0]

In [27]:
B

array([-5, -4, -4, -9], dtype=int32)